--vim.g.python3_host_prog = "/opt/homebrew/Cellar/python@3.11/3.11.4_1/bin/python3.11"

require("smierx.plugins-setup")
require("smierx.core.options")
require("smierx.core.keymaps")
require("smierx.core.colorscheme")
require("smierx.plugins.comment")
require("smierx.plugins.nvim-tree")
require("smierx.plugins.lualine")
require("smierx.plugins._telescope")
require("smierx.plugins.nvim-cmp")
require("smierx.plugins.lsp.mason")
require("smierx.plugins.lsp.lspconfig")
require("smierx.plugins.lsp.lspsaga")
require("smierx.plugins.lsp.null-ls")
require("smierx.plugins.autopairs")
require("smierx.plugins.treesitter")
require("smierx.plugins.gitsigns")
